
name: 'ACR-Migrate--$(sourceacrName)--to--$(targetacrName)--$(Date:yyyyMMdd)$(Rev:.r)'
trigger:
  - master
pr: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: sbox
    values:
      - prod
      - sbox
  - name: singleRepository
    displayName: Optional single repository to transfer
    type: string
    default: '__unset__'
  - name: letterFilters
    displayName: "Optional letter filters (for example: a-c,e)"
    type: string
    default: '__unset__'
  - name: maxRepositories
    displayName: Maximum repositories to process this run (0 = unlimited)
    type: number
    default: 5
  - name: delaySeconds
    displayName: Delay in seconds between imports
    type: number
    default: 10
  - name: dryRun
    displayName: Dry-run - Report actions without importing artifacts
    type: boolean
    default: true
  - name: forceOverwrite
    displayName: Overwrite - Force overwrite of existing tags in target registry
    type: boolean
    default: false

variables:
  ${{ if eq(parameters.environment, 'prod') }}:
    sourceacrName: hmctspublic.azurecr.io
    targetacrName: hmctsprod.azurecr.io
    serviceConnection: DCD-CNP-PROD
  ${{ if eq(parameters.environment, 'sbox') }}:
    sourceacrName: hmctssandbox.azurecr.io
    targetacrName: hmctssbox.azurecr.io
    serviceConnection: DCD-CFT-Sandbox

stages:
  - stage: Migrate
    displayName: Migrate selected ACR artifacts
    jobs:
      - job: Migrate
        displayName: "Run Migrate ACR Script - ${{ variables.sourceacrName }} to ${{ variables.targetacrName }}"
        pool:
          name: hmcts-cftptl-agent-pool
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: Execute migration script
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                cd "$(System.DefaultWorkingDirectory)"


                args=(
                  "--source-registry-name" "$(sourceacrName)"
                  "--target-registry-name" "$(targetacrName)"
                  "--max-repositories" "${{ parameters.maxRepositories }}"
                  "--delay-seconds" "${{ parameters.delaySeconds }}"
                )


                if [ "${{ parameters.singleRepository }}" != "__unset__" ]; then
                  args+=("--repository" "${{ parameters.singleRepository }}")
                fi

                if [ "${{ parameters.letterFilters }}" != "__unset__" ]; then
                  args+=("--letters" "${{ parameters.letterFilters }}")
                fi

                if [ "${{ parameters.forceOverwrite }}" = "true" ] || [ "${{ parameters.forceOverwrite }}" = "True" ]; then
                  args+=("--force")
                fi

                if [ "${{ parameters.dryRun }}" = "true" ] || [ "${{ parameters.dryRun }}" = "True" ]; then
                  args+=("--dry-run")
                fi

                echo "Running migration helper with arguments: ${args[*]}"
                python3 scripts/acr_transfer.py "${args[@]}"
