# Bulk ACR Transfer Pipeline
# Run with parameter: operation = export or import

parameters:
  - name: operation
    displayName: Operation
    type: string
    default: export
    values:
      - export
      - import
  - name: mode
    displayName: Mode
    type: string
    default: create
    values:
      - create
      - migrate
  - name: environment
    displayName: Environment
    type: string
    default: sbox
    values:
      - prod
      - sbox
  - name: platform
    displayName: Platform
    type: string
    default: cft
    values:
      - cft
      - sds

variables:
  ${{ if and(eq(parameters.environment, 'prod'), eq(parameters.platform, 'cft')) }}:
    sourceResourceGroupName:
    sourceAcrName: hmctspublic.azurecr.io
    targetResourceGroupName:
    targetAcrName: hmctsprod.azurecr.io
    sourceServiceConnection: DCD-CNP-PROD
    targetServiceConnection: DCD-CNP-PROD
  ${{ if and(eq(parameters.environment, 'prod'), eq(parameters.platform, 'sds')) }}:
    sourceResourceGroupName:
    sourceAcrName: sdshmctspublic.azurecr.io
    targetResourceGroupName:
    targetAcrName: hmctsprod.azurecr.io
    sourceServiceConnection: DTS-SHAREDSERVICES-PROD
    targetServiceConnection: DCD-CNP-PROD
  ${{ if and(eq(parameters.environment, 'sbox'), eq(parameters.platform, 'cft')) }}:
    sourceResourceGroupName:
    sourceAcrName: hmctssandbox.azurecr.io
    targetResourceGroupName:
    targetAcrName: hmctssbox.azurecr.io
    sourceServiceConnection: DCD-CFT-Sandbox
    targetServiceConnection: DCD-CFT-Sandbox
  ${{ if and(eq(parameters.environment, 'sbox'), eq(parameters.platform, 'sds')) }}:
    sourceResourceGroupName:
    sourceAcrName: sdshmctspublicsbox.azurecr.io
    targetResourceGroupName:
    targetAcrName: hmctssbox.azurecr.io
    sourceServiceConnection: DTS-SHAREDSERVICES-SBOX
    targetServiceConnection: DCD-CFT-Sandbox
  ${{ if eq(parameters.environment, 'prod') }}:
    keyVaultName:
    storageAccountName:
    storageContainerName: acrtransfer
    exportPipelineName: acrExportPipeline
    exportSecretName: acrexportsas
    importPipelineName: acrImportPipeline
    importSecretName: acrimportsas
  ${{ if eq(parameters.environment, 'sbox') }}:
    keyVaultName:
    storageAccountName:
    storageContainerName: acrtransfer
    exportPipelineName: acrExportPipeline
    exportSecretName: acrexportsas
    importPipelineName: acrImportPipeline
    importSecretName: acrimportsas


trigger: none
pr: none

jobs:
  - job: FetchManagedIdentity
    displayName: 'Fetch acrManagedIdentity from Key Vault'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureKeyVault@2
        displayName: 'Get acrManagedIdentity from Key Vault'
        inputs:
          azureSubscription: $(targetServiceConnection)
          keyVaultName: $(keyVaultName)
          secretsFilter: 'acrManagedIdentity'

  - job: BulkTransfer
    displayName: 'Bulk ACR Transfer - ${{ parameters.operation | upper }} ${{ parameters.mode | upper }}'
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: FetchManagedIdentity
    variables:
      ACR_MANAGED_IDENTITY: $(acrManagedIdentity)
    steps:
      - checkout: self

      - task: AzureCLI@2
        displayName: 'Install acrtransfer CLI extension'
        inputs:
          azureSubscription: "$(targetServiceConnection)"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az extension add --name acrtransfer
      # ExportPipeline creation
      - ${{ if and(eq(parameters.operation, 'export'), eq(parameters.mode, 'create')) }}:
        - task: AzureCLI@2
          displayName: 'Create ExportPipeline'
          env:
            ACR_MANAGED_IDENTITY: $(ACR_MANAGED_IDENTITY)
          inputs:
            azureSubscription: "$(sourceServiceConnection)"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr export-pipeline create \
                --resource-group "$(sourceResourceGroupName)" \
                --registry "$(sourceAcrName)" \
                --name "$(exportPipelineName)" \
                --secret-uri "https://$(sourceKeyVaultName).vault.azure.net/secrets/$(exportSecretName)" \
                --storage-container-uri "https://$(storageAccountName).blob.core.windows.net/$(storageContainerName)" \
                --assign-identity "$ACR_MANAGED_IDENTITY" \
                --options ContinueOnErrors

      # ExportPipeline batch migrate
      - ${{ if and(eq(parameters.operation, 'export'), eq(parameters.mode, 'migrate')) }}:
        - task: AzureCLI@2
          displayName: 'Run Batch Export Script'
          inputs:
            azureSubscription: "$(sourceServiceConnection)"
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: $(System.DefaultWorkingDirectory)
            inlineScript: |
              python3 bulk-transfer/batch_export.py \
                --resource-group $(sourceResourceGroupName) \
                --acr-name $(sourceAcrName) \
                --pipeline-name $(exportPipelineName) \
                --batch-size 50 \
                --prefix exportbatch

      # ImportPipeline creation
      - ${{ if and(eq(parameters.operation, 'import'), eq(parameters.mode, 'create')) }}:
        - task: AzureCLI@2
          displayName: 'Create ImportPipeline'
          env:
            ACR_MANAGED_IDENTITY: $(ACR_MANAGED_IDENTITY)
          inputs:
            azureSubscription: "$(targetServiceConnection)"
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr import-pipeline create \
                --resource-group "$(targetResourceGroupName)" \
                --registry "$(targetAcrName)" \
                --name "$(importPipelineName)" \
                --secret-uri "https://$(keyVaultName).vault.azure.net/secrets/$(importSecretName)" \
                --storage-container-uri "https://$(storageAccountName).blob.core.windows.net/$(storageContainerName)" \
                --assign-identity "$ACR_MANAGED_IDENTITY" \
                --options ContinueOnErrors

      # ImportPipeline batch migrate
      - ${{ if and(eq(parameters.operation, 'import'), eq(parameters.mode, 'migrate')) }}:
        - task: AzureCLI@2
          displayName: 'Run Batch Import Script'
          inputs:
            azureSubscription: "$(targetServiceConnection)"
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: $(System.DefaultWorkingDirectory)
            inlineScript: |
              python3 bulk-transfer/batch_import.py \
                --resource-group $(targetResourceGroupName) \
                --acr-name $(targetAcrName) \
                --pipeline-name $(importPipelineName) \
                --storage-account $(storageAccountName) \
                --container $(storageContainerName) \
                --prefix importbatch
